# Generated by Django 5.2.5 on 2025-08-11 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código do Cupom')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Desconto')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentagem'), ('FIXED', 'Fixo')], max_length=15, verbose_name='Tipo de desconto')),
                ('maximum_uses', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Máximo de Usos')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Data de ativação')),
                ('deactivation_date', models.DateField(blank=True, null=True, verbose_name='Data de desativação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('cycle', models.CharField(choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal'), ('BIMONTHLY', 'Bimestral'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUALLY', 'Semestral'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=15, verbose_name='Ciclo')),
                ('billing_type', models.CharField(choices=[('UNDEFINED', 'Indefinido'), ('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão de Crédito'), ('PIX', 'Pix')], default='CREDIT_CARD', max_length=15, verbose_name='Tipo de Cobrança')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('free_period', models.PositiveSmallIntegerField(default=0, verbose_name='Período Gratuito')),
                ('refund_period', models.PositiveSmallIntegerField(default=7, verbose_name='Período de Reembolso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True, verbose_name='Código do Evento')),
                ('payload', models.JSONField(verbose_name='Payload do Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=30, unique=True, verbose_name='Código do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=30, unique=True, verbose_name='Código da Assinatura')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('EXPIRED', 'Expirada')], default='INACTIVE', max_length=15, verbose_name='Status da Assinatura')),
                ('next_due', models.DateField(verbose_name='Próximo Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payment.coupon', verbose_name='Cupom')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payment.customer', verbose_name='Código do Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payment.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=30, unique=True, verbose_name='Código da Cobrança')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmado'), ('PENDING', 'Pendente'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=30, verbose_name='Status da Cobrança')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.subscription', verbose_name='Código da Assinatura')),
            ],
            options={
                'verbose_name': 'cobrança',
                'verbose_name_plural': 'cobranças',
            },
        ),
    ]
